# Site settings
title: 少华博客
email: hzlaishaohua@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  少华博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://hzlaishaohua.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Shaohua Lai

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: hzlaishaohua
weibo: hzlaishaohua
github: hzlaishaohua
instagram: hzlaishaohua
linkedin: hzlaishaohua

# avatar and Favicon
avatar: /assets/img/lz.jpg
favicon: /assets/img/lzxx.jpg

# disqus config
disqus:
  shortname: laishaohua-zh

# google analytics config
ga:
  id: UA-54767140-1
  url: laishaohau.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: rdiscount
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
